name: Spring Boot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # or 'gradle' if using Gradle

      - name: Build with Maven
        run: mvn clean install

      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mummoorthins/springboot-cicd-example
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
